version: '2'
services:
  accountancy-app:
    image: accountancy
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://accountancy-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=accountancy
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  accountancy-mongodb:
    extends:
      file: mongodb.yml
      service: accountancy-mongodb
